version: "3.9"

services:
  api:
    env_file: .env
    image: djmolitor/adaptive_fastapi_polcand
    depends_on:
      - database
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
  
  app:
    env_file: .env
    image: djmolitor/adaptive_shiny_polcand
    depends_on:
      - database
    networks:
      - frontend
    ports:
      - "8000:8000"

  database:
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: "postgres:16.1-bullseye"
    networks:
      - backend
    user: postgres

networks:
  frontend:
  backend:
