name: adaptive_survey

services:
  database:
    image: postgres:16.1-bullseye
    container_name: database
    environment:
      POSTGRES_PASSWORD: abc
    # expose:
    #   - "5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    #   - "5432:5432"

  api:
    image: adaptive-fastapi
    container_name: api
    build: ./api
    depends_on:
      database:
        condition: service_healthy
    # expose:
    #   - "80"
    networks:
      - backend
    # ports:
    #   - "80:80"
  
  app:
    image: adaptive-shiny
    container_name: app
    build: ./ui
    depends_on:
      database:
        condition: service_healthy
      api:
        condition: service_started
    networks:
      - backend
    ports:
      - "8000:8000"

networks:
  backend: