name: adaptive_survey

services:
  api:
    build: ./api
    container_name: api
    environment:
      API_CONTAINER_PORT: "${API_CONTAINER_PORT}"
      POSTGRES_HOST_PORT: "${POSTGRES_HOST_PORT}"
      POSTGRES_PASS: "${POSTGRES_PASS}"
      POSTGRES_USER_NAME: "${POSTGRES_USER_NAME}"
    depends_on:
      database:
        condition: service_healthy
    image: adaptive_fastapi
    networks:
      - backend
      - frontend
    ports:
      - "${API_CONTAINER_PORT}:${API_HOST_PORT}"
  
  app:
    build: ./ui
    container_name: app
    depends_on:
      database:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      API_HOST_PORT: "${API_HOST_PORT}"
      APP_CONTAINER_PORT: "${APP_CONTAINER_PORT}"
    image: adaptive_shiny
    networks:
      - frontend
    ports:
      - "${APP_CONTAINER_PORT}:${APP_HOST_PORT}"

  database:
    container_name: database
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_USER: "${POSTGRES_USER_NAME}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: "postgres:${POSTGRES_VERSION}"
    networks:
      - backend
    ports:
      - "${POSTGRES_CONTAINER_PORT}:${POSTGRES_HOST_PORT}"
    user: "${POSTGRES_USER_NAME}"

networks:
  frontend:
  backend: